
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:urn="urn:uniface:applic:wrapped:services:WS_GRIN_FRCST" xmlns:urn1="urn:uniface:applic:services:MAALEGR_FRCST_TRNS">
   <soapenv:Header/>
   <soapenv:Body>
      <urn:CREATEFRCST>
         <urn:GENERATED_PARAMETER_NAME_1>
            <!--Zero or more repetitions:-->
            <urn1:MAALEGR_FRCST_TRNSType>
               <!--You may enter the following 36 items in any order-->
               <urn1:FIRM_CODE>1</urn1:FIRM_CODE>
               <urn1:CUST_CODE>601067000</urn1:CUST_CODE>
               <urn1:WEB_FORCST>123456789</urn1:WEB_FORCST>
               <urn1:LINE_NBR>1</urn1:LINE_NBR>
               <!--Optional:-->
               <urn1:STRM_CODE>06</urn1:STRM_CODE>
               <!--Optional:-->
               <urn1:RQSTD_SHIP_DATE>2025-12-01T10:50:39.838Z</urn1:RQSTD_SHIP_DATE>
               <!--Optional:-->
               <urn1:PART_CODE>59309636</urn1:PART_CODE>
               <!--Optional:-->
               <urn1:UNIT_CODE>11</urn1:UNIT_CODE>
               <!--Optional:-->
               <urn1:QNTY>1</urn1:QNTY>
               <!--Optional:-->
               <urn1:PART_PRC>50.5</urn1:PART_PRC>
               <!--Optional:-->
               <urn1:AMNT_BFOR_RDCT>50.5</urn1:AMNT_BFOR_RDCT>
               <!--Optional:-->
               <urn1:RDCT_AMNT>0</urn1:RDCT_AMNT>
               <!--Optional:-->
               <urn1:RDCT_PCNT>0</urn1:RDCT_PCNT>
               <!--Optional:-->
               <urn1:AMNT_AFTR_RDCT>50.5</urn1:AMNT_AFTR_RDCT>
               <!--Optional:-->
               <urn1:VAT_AMNT>17</urn1:VAT_AMNT>
               <!--Optional:-->
               <urn1:AMNT_AFTR_TAX_RDCT>50.5</urn1:AMNT_AFTR_TAX_RDCT>
               <!--Optional:-->
               <urn1:PSEUDO_PHAN_Y_N>ל</urn1:PSEUDO_PHAN_Y_N>
               <!--Optional:-->
               <urn1:PICKUP_Y_N>1</urn1:PICKUP_Y_N>
               <!--Optional:-->
               <urn1:PAID_UP_Y_N>Y</urn1:PAID_UP_Y_N>
               <!--Optional:-->
               <urn1:DOC_RMRK>abc</urn1:DOC_RMRK>
               <!--Optional:-->
               <urn1:REFE>123456716</urn1:REFE>
               <!--Optional:-->
               <urn1:RCVR_NAME>a</urn1:RCVR_NAME>
               <!--Optional:-->
               <urn1:STREET_TO_SHIP>a</urn1:STREET_TO_SHIP>
               <!--Optional:-->
               <urn1:QTR_TO_SHIP>a</urn1:QTR_TO_SHIP>
               <!--Optional:-->
               <urn1:CITY_TO_SHIP>a</urn1:CITY_TO_SHIP>
               <!--Optional:-->
               <urn1:ZIP_TO_SHIP>123</urn1:ZIP_TO_SHIP>
               <!--Optional:-->
               <urn1:H_AREA_PHON_CODE_TO_SHIP>12345</urn1:H_AREA_PHON_CODE_TO_SHIP>
               <!--Optional:-->
               <urn1:H_PHON_TO_SHIP>1234</urn1:H_PHON_TO_SHIP>
               <!--Optional:-->
               <urn1:AREA_PHON_CODE_TO_SHIP>1234</urn1:AREA_PHON_CODE_TO_SHIP>
               <!--Optional:-->
               <urn1:PHON_TO_SHIP>1222</urn1:PHON_TO_SHIP>
               <!--Optional:-->
               <urn1:MAIL>irena@one.co.il</urn1:MAIL>
               <!--Optional:-->
               <urn1:CEL_AREA_PHONE_CODE>054</urn1:CEL_AREA_PHONE_CODE>
               <!--Optional:-->
               <urn1:CEL_PHONE>444</urn1:CEL_PHONE>
               <!--Optional:-->
               <urn1:ID_WEB_FRCST>123456737</urn1:ID_WEB_FRCST>
               <!--Optional:-->
               <urn1:DLVRY_TYPE_DSCR>122</urn1:DLVRY_TYPE_DSCR>
               <!--Optional:-->
               <urn1:ALWAYS_IN_STOCK>0</urn1:ALWAYS_IN_STOCK>
            </urn1:MAALEGR_FRCST_TRNSType>
         </urn:GENERATED_PARAMETER_NAME_1>
         <urn:ID>signat1,g#5141#AF</urn:ID>
      </urn:CREATEFRCST>
   </soapenv:Body>
</soapenv:Envelope>