// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ijgrelgzahireresdqvw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqZ3JlbGd6YWhpcmVyZXNkcXZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk0ODcyNzAsImV4cCI6MjA3NTA2MzI3MH0.-b3BECfdSeWk0WLNwNVEa6RyDw12sjsLzGDhJi_oNB8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});